import { defineField, defineType } from "sanity";

export default defineType({
  name: "scholarship",
  title: "Scholarship",
  type: "document",
  groups: [
    { name: "content", title: "Content" },
    { name: "details", title: "Scholarship Details" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "featuredImage",
      title: "Featured Image",
      type: "image",
      group: "content",
      options: { hotspot: true },
      fields: [{ name: "alt", title: "Alt text", type: "string" }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "excerpt",
      title: "Short Excerpt",
      type: "text",
      rows: 3,
      group: "content",
      description: "Used in cards and meta description if none set.",
    }),
    defineField({
      name: "body",
      title: "Full Article Body",
      type: "array",
      group: "content",
      of: [{ type: "block" }, { type: "image", options: { hotspot: true } }],
    }),
    defineField({
      name: "country",
      title: "Country",
      type: "reference",
      to: [{ type: "country" }],
      group: "details",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "categories",
      title: "Categories",
      type: "array",
      of: [{ type: "reference", to: [{ type: "category" }] }],
      group: "details",
    }),
    defineField({
      name: "university",
      title: "University",
      type: "string",
      group: "details",
    }),
    defineField({
      name: "provider",
      title: "Scholarship Provider",
      type: "string",
      group: "details",
    }),
    defineField({
      name: "degreeLevel",
      title: "Degree Level",
      type: "string",
      group: "details",
      options: {
        list: [
          { title: "Bachelor's", value: "bachelors" },
          { title: "Master's", value: "masters" },
          { title: "PhD", value: "phd" },
          { title: "Fellowship", value: "fellowship" },
          { title: "Internship", value: "internship" },
          { title: "Exchange Program", value: "exchange" },
          { title: "Competition", value: "competition" },
        ],
      },
    }),
    defineField({
      name: "fundingType",
      title: "Funding Type",
      type: "string",
      group: "details",
      options: {
        list: [
          { title: "Fully Funded", value: "fully-funded" },
          { title: "Partially Funded", value: "partially-funded" },
          { title: "Tuition Only", value: "tuition-only" },
        ],
      },
    }),
    defineField({
      name: "eligibleCountries",
      title: "Eligible Countries",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
    }),
    defineField({
      name: "deadline",
      title: "Application Deadline",
      type: "date",
      group: "details",
    }),
    defineField({
      name: "benefits",
      title: "Benefits",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
    }),
    defineField({
      name: "eligibility",
      title: "Eligibility Requirements",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
    }),
    defineField({
      name: "requiredDocuments",
      title: "Required Documents",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
    }),
    defineField({
      name: "applicationProcess",
      title: "Application Process",
      type: "array",
      of: [{ type: "block" }],
      group: "details",
    }),
    defineField({
      name: "applicationLink",
      title: "Official Application Link",
      type: "url",
      group: "details",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "featured",
      title: "Featured on Homepage",
      type: "boolean",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "relatedScholarships",
      title: "Related Scholarships",
      type: "array",
      of: [{ type: "reference", to: [{ type: "scholarship" }] }],
      group: "details",
    }),
    defineField({
      name: "publishedAt",
      title: "Published At",
      type: "datetime",
      group: "content",
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: "seoTitle",
      title: "SEO Title",
      type: "string",
      group: "seo",
    }),
    defineField({
      name: "seoDescription",
      title: "SEO Description",
      type: "text",
      rows: 2,
      group: "seo",
    }),
  ],
  preview: {
    select: { title: "title", media: "featuredImage", subtitle: "country.name" },
  },
});
